"""initial migration

Revision ID: c8c5f46ff3c5
Revises: 
Create Date: 2023-11-20 15:46:58.052261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8c5f46ff3c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('locationId', sa.Integer(), nullable=False),
    sa.Column('locationTitle', sa.String(length=500), nullable=True),
    sa.Column('locationDescription', sa.Text(), nullable=True),
    sa.Column('accessible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('locationId')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=500), nullable=True),
    sa.Column('password', sa.String(length=500), nullable=True),
    sa.Column('institution', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('topic', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('startDate', sa.String(length=500), nullable=True),
    sa.Column('startTime', sa.String(length=500), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('meetingLocation', sa.Integer(), nullable=True),
    sa.Column('institution', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['meetingLocation'], ['location.locationId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user__group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('creator', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user__group')
    op.drop_table('group')
    op.drop_table('user')
    op.drop_table('location')
    # ### end Alembic commands ###
